services:
  cashbook4:
    container_name: cashbook4
    depends_on:
      - "postgres"
    image: dingdangdog/cashbook:4.0.1
    restart: always
    # network_mode: "host"
    volumes:
      - ./data:/app/data # 数据挂载到本地，目前只会存储小票数据，不建议修改
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@cashbook_db:5432/cashbook?schema=public" # 数据库链接，【请自行修改！与你的数据库一致】
      NUXT_DATA_PATH: "/app/data" # 数据存储未知，现在只有小票图片了，不建议修改
      NUXT_APP_URL: "https://cashbook.oldmoon.top" # 服务根路径，如果有端口号，需要加上端口号
      NUXT_AUTH_ORIGIN: "https://cashbook.oldmoon.top/api/auth" # 登录授权相关接口地址 【请自行修改域名/IP！最后要以 /api/auth 结尾！】
      NUXT_AUTH_SECRET: "lazycat" # 前台登录加密使用的密钥 【自行修改！】
      NUXT_ADMIN_USERNAME: "admin" # 后台登录用户名
      # 【自行修改】后他登录密码，密码是加密后的，生成密码可前往 https://cashbook.oldmoon.top/admin/GetPassword 或独立部署后访问 `你的url/admin/GetPassword`
      NUXT_ADMIN_PASSWORD: "fb35e9343a1c095ce1c1d1eb6973dc570953159441c3ee315ecfefb6ed05f4cc"
    ports:
      - 9090:9090 # 账本开放端口 【自行修改！】

  postgres:
    container_name: cashbook_db
    image: registry.lazycat.cloud/postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cashbook
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # 如果您已有PostgreSQL运行在5432端口，可以修改为其他端口，例如"5433:5432"

volumes:
  postgres_data:
    driver: local
